version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: healthcare-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./server
    container_name: healthcare-backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/healthcare
      - PORT=5000
    depends_on:
      - mongodb
    env_file:
      - .env
    volumes:
      - ./server:/app
      - /app/node_modules

  frontend:
    build: ./client
    container_name: healthcare-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    stdin_open: true
    tty: true
    volumes:
      - ./client:/app
      - /app/node_modules

volumes:
  mongo-data:
